import { StaticImageData } from "next/image";

export const members = [
  {
    year: 2025,
    name: "Geeth Induwara",
    image:
      require("@/assets/bc-and-excom/excom/2025/Geeth-induwara.png") as StaticImageData,
    title: "Chairperson - IEEE Student Branch",
    linkdInURL: "",
    facebookURL: "",
    role: "chairperson",
    category: "sb",
  },
  {
    year: 2025,
    name: "Jayasanka Ariyaratna",
    image:
      require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
    title: "Chairperson - IEEE Computer Society",
    linkdInURL: "",
    facebookURL: "",
    role: "chairperson",
    category: "cs",
  },
  {
    year: 2025,
    name: "Pasandi Samarasinghe",
    image:
      require("@/assets/bc-and-excom/excom/2025/pasandi-samarasinghe.png") as StaticImageData,
    title: "Chairperson - IEEE Women In Engineering",
    linkdInURL: "",
    facebookURL: "",
    role: "chairperson",
    category: "wie",
  },
  {
    year: 2025,
    name: "Jayasanka Ariyaratna",
    image:
      require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
    title: "Vice Chairperson",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Pasandi Samarasinghe",
    image:
      require("@/assets/bc-and-excom/excom/2025/pasandi-samarasinghe.png") as StaticImageData,
    title: "Secretary",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Sithum Sankajith",
    image:
      require("@/assets/bc-and-excom/excom/2025/sithum-sankajith.png") as StaticImageData,
    title: "Treasurer",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Thilarah Gunarathne",
    image:
      require("@/assets/bc-and-excom/excom/2025/thilarah-gunarathne.png") as StaticImageData,
    title: "Assistant Secretary",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },

  {
    year: 2025,
    name: "Kumuditha Ranasinghe",
    image:
      require("@/assets/bc-and-excom/excom/2025/kumuditha-ranasinghe.png") as StaticImageData,
    title: "Web Master",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Dasun Sri Nethmal",
    image:
      require("@/assets/bc-and-excom/excom/2025/dasun-sri-nethmal.png") as StaticImageData,
    title: "Designer",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Ravindu Rajapaksha",
    image:
      require("@/assets/bc-and-excom/excom/2025/ravindu-rajapaksha.png") as StaticImageData,
    title: "Event Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Sisila Dhevasiri",
    image:
      require("@/assets/bc-and-excom/excom/2025/sisila-dhevasiri.png") as StaticImageData,
    title: "Media Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Hiruni Athukorala",
    image:
      require("@/assets/bc-and-excom/excom/2025/hiruni-athukorala.png") as StaticImageData,
    title: "Volunteer Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Naveesha Thathsarani",
    image:
      require("@/assets/bc-and-excom/excom/2025/naveesha-thathsarani.png") as StaticImageData,
    title: "Excom member",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Sakuni Sirimanna",
    image:
      require("@/assets/bc-and-excom/excom/2025/sakuni-sirimanna.png") as StaticImageData,
    title: "Excom member",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Vilanya Udukumbura",
    image:
      require("@/assets/bc-and-excom/excom/2025/vilanya-udukumbura.png") as StaticImageData,
    title: "Excom member",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Hashini Wickramarachchi",
    image:
      require("@/assets/bc-and-excom/excom/2025/hashini-wickramarachchi.png") as StaticImageData,
    title: "Excom member",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Vihangi Yapa",
    image:
      require("@/assets/bc-and-excom/excom/2025/vihangi-yapa.png") as StaticImageData,
    title: "Excom member",
    linkdInURL: "",
    facebookURL: "",
    category: "sb",
  },
  {
    year: 2025,
    name: "Dasunika Yapabandara",
    image:
      require("@/assets/bc-and-excom/excom/2025/dasunika-yapabandara.png") as StaticImageData,
    title: "Vice Chair - FOC",
    linkdInURL: "",
    facebookURL: "",
    category: "wie",
  },
  {
    year: 2025,
    name: "Linaya Gunawardena",
    image:
      require("@/assets/bc-and-excom/excom/2025/linaya-gunawardena.png") as StaticImageData,
    title: "Vice Chair- FOE",
    linkdInURL: "",
    facebookURL: "",
    category: "wie",
  },
  {
    year: 2025,
    name: "Hansika Keeragala",
    image:
      require("@/assets/bc-and-excom/excom/2025/hansika-keeragala.png") as StaticImageData,
    title: "Secretary",
    linkdInURL: "",
    facebookURL: "",
    category: "wie",
  },
  {
    year: 2025,
    name: "Thathsarani Dhalanjala",
    image:
      require("@/assets/bc-and-excom/excom/2025/thathsarani-dhalanjala.png") as StaticImageData,
    title: "Assistant Secretary",
    linkdInURL: "",
    facebookURL: "",
    category: "wie",
  },
  {
    year: 2025,
    name: "Navodya Hansini",
    image:
      require("@/assets/bc-and-excom/excom/2025/navodya-hansini.png") as StaticImageData,
    title: "Assistant Treasurer",
    linkdInURL: "",
    facebookURL: "",
    category: "wie",
  },
  {
    year: 2025,
    name: "Kaveesha Nethmini",
    image:
      require("@/assets/bc-and-excom/excom/2025/kaveesha-nethmini.png") as StaticImageData,
    title: "Designer",
    linkdInURL: "",
    facebookURL: "",
    category: "wie",
  },
  {
    year: 2025,
    name: "Benoli Senanayaka",
    image:
      require("@/assets/bc-and-excom/excom/2025/benoli-senanayaka.png") as StaticImageData,
    title: "Event Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "wie",
  },
  {
    year: 2025,
    name: "Dinuri Jayaweera",
    image:
      require("@/assets/bc-and-excom/excom/2025/dinuri-jayaweera.png") as StaticImageData,
    title: "Publicity Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "wie",
  },
  {
    year: 2025,
    name: "Limasha Sathsara",
    image:
      require("@/assets/bc-and-excom/excom/2025/limasha-sathsara.png") as StaticImageData,
    title: "Vice Chairperson",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Jasmi Pavithra",
    image:
      require("@/assets/bc-and-excom/excom/2025/jasmi-pavithra.png") as StaticImageData,
    title: "Secretary",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Pramith Charuka",
    image:
      require("@/assets/bc-and-excom/excom/2025/pramith-charuka.png") as StaticImageData,
    title: "Assistant Treasurer",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Tharundi Pawani",
    image:
      require("@/assets/bc-and-excom/excom/2025/tharundi-pawani.png") as StaticImageData,
    title: "Assistant Secretary",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Nipuni Theekshana",
    image:
      require("@/assets/bc-and-excom/excom/2025/nipuni-theekshana.png") as StaticImageData,
    title: "Volunter Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Lahiru Ediriweera",
    image:
      require("@/assets/bc-and-excom/excom/2025/lahiru-ediriweera.png") as StaticImageData,
    title: "Event Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Dilmi Manodhya",
    image:
      require("@/assets/bc-and-excom/excom/2025/dilmi-manodhya.png") as StaticImageData,
    title: "Industry Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Tharindu Ethpatiyawa",
    image:
      require("@/assets/bc-and-excom/excom/2025/tharindu-ethpatiyawa.png") as StaticImageData,
    title: "Media Coordinator",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Dasun Sri Nethmal",
    image:
      require("@/assets/bc-and-excom/excom/2025/dasun-sri-nethmal.png") as StaticImageData,
    title: "Creative Content Committee Lead",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Yasiru Dharmathilaka",
    image:
      require("@/assets/bc-and-excom/excom/2025/yasiru-dharmathilaka.png") as StaticImageData,
    title: "Development Committee Lead",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Sasindu Nilupul",
    image:
      require("@/assets/bc-and-excom/excom/2025/sasindu-nilupul.png") as StaticImageData,
    title: "Research Committee Lead",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Anuja Rathnayaka",
    image:
      require("@/assets/bc-and-excom/excom/2025/anuja-rathnayaka.png") as StaticImageData,
    title: "Creative Content Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Tharindu Thilakshana",
    image:
      require("@/assets/bc-and-excom/excom/2025/tharindu-thilakshana-de-zoysa.png") as StaticImageData,
    title: "Creative Content Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Manuja Demin",
    image:
      require("@/assets/bc-and-excom/excom/2025/manuja-demin.png") as StaticImageData,
    title: "Creative Content Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Ometh Abeyrathne",
    image:
      require("@/assets/bc-and-excom/excom/2025/ometh-abeyrathne.png") as StaticImageData,
    title: "Development Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Navindu Disanayaka",
    image:
      require("@/assets/bc-and-excom/excom/2025/navindu-disanayaka.png") as StaticImageData,
    title: "Development Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Nipun Avishka",
    image:
      require("@/assets/bc-and-excom/excom/2025/nipun-avishka.png") as StaticImageData,
    title: "Development Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Navodhya Senali",
    image:
      require("@/assets/bc-and-excom/excom/2025/navodhya-senali.png") as StaticImageData,
    title: "Research Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Malki Munasinghe",
    image:
      require("@/assets/bc-and-excom/excom/2025/malki-munasinghe.png") as StaticImageData,
    title: "Research Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Sineth Hasintha",
    image:
      require("@/assets/bc-and-excom/excom/2025/sineth-hasintha.png") as StaticImageData,
    title: "Research Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Lakindu Cabral",
    image:
      require("@/assets/bc-and-excom/excom/2025/lakindu-cabral.png") as StaticImageData,
    title: "Research Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Nadeesha Thathsarani",
    image:
      require("@/assets/bc-and-excom/excom/2025/nadeesha-thathsarani.png") as StaticImageData,
    title: "Research Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Udara Rathnapala",
    image:
      require("@/assets/bc-and-excom/excom/2025/udara-rathnapala.png") as StaticImageData,
    title: "Research Committee Members",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  {
    year: 2025,
    name: "Prabani Vinodya",
    image:
      require("@/assets/bc-and-excom/excom/2025/prabani-vinodya.png") as StaticImageData,
    title: "Research Committee Member",
    linkdInURL: "",
    facebookURL: "",
    category: "cs",
  },
  // {
  //   year: 2024,
  //   name: "Chathuranga Senarathne",
  //   imageUrl: "/images/excom/2024/chathuranga-senarathne.jpg",
  //   title: "Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Abhishek Rathnayaka",
  //   imageUrl: "/images/excom/2024/abhishek-rathnayaka.jpg",
  //   title: "Vice Chair-FOC",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Dewmi Hathurusingha",
  //   imageUrl: "/images/excom/2024/dewmi-hathurusingha.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Hansika Keeragala",
  //   imageUrl: "/images/excom/2024/hansika-keeragala.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Dhanuka Wickramage",
  //   imageUrl: "/images/excom/2024/dhanuka-wickramage.jpg",
  //   title: "Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Geeth Induwara",
  //   imageUrl: "/images/excom/2024/geeth-induwara.jpg",
  //   title: "Assistant Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Ishan Dulanjana",
  //   imageUrl: "/images/excom/2024/ishan-dulanjana.jpg",
  //   title: "Web Master",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Limasha Sathsara",
  //   imageUrl: "/images/excom/2024/limasha-sathsara.jpg",
  //   title: "Designer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Malinda Kawshalya",
  //   imageUrl: "/images/excom/2024/malinda-kawshalya.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Tharindu Dhanushka",
  //   imageUrl: "/images/excom/2024/tharindu-dhanushka.jpg",
  //   title: "Media Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Ishara Dias",
  //   imageUrl: "/images/excom/2024/ishara-dias.jpg",
  //   title: "Volunteer Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Dewmi Hathurusingha",
  //   imageUrl: "/images/excom/2024/dewmi-hathurusingha.jpg",
  //   title: "Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Pasandi Samarasinghe",
  //   imageUrl: "/images/excom/2024/pasandi-samarasinghe.jpg",
  //   title: "Vice Chair - FOC",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Sewmini Lenora",
  //   imageUrl: "/images/excom/2024/sewmini-lenora.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Jasmi Pavithra",
  //   imageUrl: "/images/excom/2024/jasmi-pavithra.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Dasunika Yapabandara",
  //   imageUrl: "/images/excom/2024/dasunika-yapabandara.jpg",
  //   title: "Assistant Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Thathsarani Dhalanjala",
  //   imageUrl: "/images/excom/2024/thathsarani-dhalanjala.jpg",
  //   title: "Designer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Ayodya Weerabahu",
  //   imageUrl: "/images/excom/2024/ayodya-weerabahu.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Hiruni Athukorala",
  //   imageUrl: "/images/excom/2024/hiruni-athukorala.jpg",
  //   title: "Publicity Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Abhishek Rathnayaka",
  //   imageUrl: "/images/excom/2024/abhishek-rathnayaka.jpg",
  //   title: "Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Jayasanka Ariyarathna",
  //   imageUrl: "/images/excom/2024/jayasanka-ariyarathna.jpg",
  //   title: "Vice Chair-FOC",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Pasandi Samarasinghe",
  //   imageUrl: "/images/excom/2024/pasandi-samarasinghe.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Malinda Kawshalya",
  //   imageUrl: "/images/excom/2024/malinda-kawshalya.jpg",
  //   title: "Assistant Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Githmi Senani",
  //   imageUrl: "/images/excom/2024/githmi-senani.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Kavishka Sasindu",
  //   imageUrl: "/images/excom/2024/kavishka-sasindu.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Geeth Induwara",
  //   imageUrl: "/images/excom/2024/geeth-induwara.jpg",
  //   title: "Industry Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Ishara Bhagya",
  //   imageUrl: "/images/excom/2024/ishara-bhagya.jpg",
  //   title: "Creative Content Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Akshitha Sriyanjith",
  //   imageUrl: "/images/excom/2024/akshitha-sriyanjith.jpg",
  //   title: "Development Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Bakthi Gamage",
  //   imageUrl: "/images/excom/2024/bakthi-gamage.jpg",
  //   title: "Research Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Pramith Charuka",
  //   imageUrl: "/images/excom/2024/pramith-charuka.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Sithum Sankajith",
  //   imageUrl: "/images/excom/2024/sithum-sankajith.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Sasindu Nilupul",
  //   imageUrl: "/images/excom/2024/sasindu-nilupul.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Lahiru Nimesh Ediriweera",
  //   imageUrl: "/images/excom/2024/lahiru-nimesh-ediriweera.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Dulmin shanika wickramage",
  //   imageUrl: "/images/excom/2024/dulmin-shanika-wickramage.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Ranudi Kariyapperuma",
  //   imageUrl: "/images/excom/2024/ranudi-kariyapperuma.jpg",
  //   title: "Development Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Gayantha Nadeemal",
  //   imageUrl: "/images/excom/2024/gayantha-nadeemal.jpg",
  //   title: "Development Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Ayodya Weerabahu",
  //   imageUrl: "/images/excom/2024/ayodya-weerabahu.jpg",
  //   title: "Creative Content Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
];
