import { StaticImageData } from "next/image";

export const members = [
  {
    year: 2025,
    name: "Geeth Induwara",
    image:
      require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
    title: "Chairperson - IEEE Student Branch",
    linkdInURL: "",
    facebookURL: "",
    role: "chairperson",
    category: "sb",
  },
  {
    year: 2025,
    name: "Jayasanka Ariyaratna",
    image:
      require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
    title: "Chairperson - IEEE Computer Society",
    linkdInURL: "",
    facebookURL: "",
    role: "chairperson",
    category: "cs",
  },
  {
    year: 2025,
    name: "Pasnadi Samarasinghe",
    image:
      require("@/assets/bc-and-excom/excom/2025/pasnadi-samarasinghe.png") as StaticImageData,
    title: "Chairperson - IEEE Women In Engineering",
    linkdInURL: "",
    facebookURL: "",
    role: "chairperson",
    category: "wie",
  },
  // {
  //   year: 2025,
  //   name: "Geeth Induwara",
  //   image:
  //     require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
  //   title: "Chairperson - IEEE Student Branch",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },{
  //   year: 2025,
  //   name: "Geeth Induwara",
  //   image:
  //     require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
  //   title: "Chairperson - IEEE Student Branch",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },{
  //   year: 2025,
  //   name: "Geeth Induwara",
  //   image:
  //     require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
  //   title: "Chairperson - IEEE Student Branch",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Jayasanka Ariyaratna",
  //   image:
  //     require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
  //   title: "Chairperson - IEEE Computer Society",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Jayasanka Ariyaratna",
  //   image:
  //     require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
  //   title: "Chairperson - IEEE Computer Society",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Jayasanka Ariyaratna",
  //   image:
  //     require("@/assets/bc-and-excom/excom/2025/jayasanka-ariyaratna.png") as StaticImageData,
  //   title: "Chairperson - IEEE Computer Society",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },

  // {
  //   year: 2025,
  //   name: "Geeth Induwara",
  //   imageUrl: "/images/excom/2025/Geeth-induwara.jpg",
  //   title: "Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Jayasanka Ariyaratna",
  //   imageUrl: "/images/excom/2025/jayasanka-ariyaratna.jpg",
  //   title: "Vice Chair",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Pasadi Samarasinghe",
  //   imageUrl: "/images/excom/2025/pasadi-samarasinghe.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Sithum Sankajith",
  //   imageUrl: "/images/excom/2025/sithum-sankajith.jpg",
  //   title: "Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Thilarah Gunarathne",
  //   imageUrl: "/images/excom/2025/thilarah-gunarathne.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  //
  // {
  //   year: 2025,
  //   name: "Kumuditha Ranasinghe",
  //   imageUrl: "/images/excom/2025/kumiditha-ranasinghe.jpg",
  //   title: "Web Master",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Dasun Sri Nethmal",
  //   imageUrl: "/images/excom/2025/dasun-sri-nethmal.jpg",
  //   title: "Designer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Ravindu Rajapaksha",
  //   imageUrl: "/images/excom/2025/ravindu-rajapaksha.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Sisila Dhevasiri",
  //   imageUrl: "/images/excom/2025/sisila-dhevasiri.jpg",
  //   title: "Media Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Hiruni Athukorala",
  //   imageUrl: "/images/excom/2025/hiruni-athukorala.jpg",
  //   title: "Volunteer Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Naveesha Thathsarani",
  //   imageUrl: "/images/excom/2025/naveesha-thathsarani.jpg",
  //   title: "Excom member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Sakuni Sirimanna",
  //   imageUrl: "/images/excom/2025/sakuni-sirimanna.jpg",
  //   title: "Excom member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Vilanya Udukumbura",
  //   imageUrl: "/images/excom/2025/vilanya-udukumbura.jpg",
  //   title: "Excom member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Vihangi Yapa",
  //   imageUrl: "/images/excom/2025/vihangi-yapa.jpg",
  //   title: "Excom member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2025,
  //   name: "Pasadi Samarasinghe",
  //   imageUrl: "/images/excom/2025/pasadi-samarasinghe.jpg",
  //   title: "Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Dasunika Yapabandara",
  //   imageUrl: "/images/excom/2025/dasunika-yapabandara.jpg",
  //   title: "Vice Chair - FOC",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Linaya Gunawardena",
  //   imageUrl: "/images/excom/2025/linaya-gunawardena.jpg",
  //   title: "Vice Chair- FOE",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Hansika Keeragala",
  //   imageUrl: "/images/excom/2025/hansika-keeragala.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Thathsarani Dhalanjala",
  //   imageUrl: "/images/excom/2025/thathsarani-dhalanjala.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Navodya Hansini",
  //   imageUrl: "/images/excom/2025/navodya-hansini.jpg",
  //   title: "Assistant Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Kaveesha Nethmini",
  //   imageUrl: "/images/excom/2025/kaveesha-nethmini.jpg",
  //   title: "Designer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Benoli Senanayaka",
  //   imageUrl: "/images/excom/2025/benoli-senanayaka.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Dinuri Jayaweera",
  //   imageUrl: "/images/excom/2025/dinuri-jayaweera.jpg",
  //   title: "Publicity Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2025,
  //   name: "Jayasanka Ariyaratne",
  //   imageUrl: "/images/excom/2025/jayasanka-ariyaratne.jpg",
  //   title: "ChairPerson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Limasha Sathsara",
  //   imageUrl: "/images/excom/2025/limasha-sathsara.jpg",
  //   title: "Vice Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Jasmi Pavithra",
  //   imageUrl: "/images/excom/2025/jasmi-pavithra.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Pramith Charuka",
  //   imageUrl: "/images/excom/2025/pramith-charuka.jpg",
  //   title: "Assistant Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Tharundi Pawani",
  //   imageUrl: "/images/excom/2025/tharundi-pawani.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Nipuni Theekshana",
  //   imageUrl: "/images/excom/2025/nipuni-theekshana.jpg",
  //   title: "Volunter Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Lahiru Ediriweera",
  //   imageUrl: "/images/excom/2025/lahiru-ediriweera.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Dilini Manodhya",
  //   imageUrl: "/images/excom/2025/dilini-manodhya.jpg",
  //   title: "Industry Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Tharindu Ethpatiyawa",
  //   imageUrl: "/images/excom/2025/tharindu-ethpatiyawa.jpg",
  //   title: "Media Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Dasun Sri Nethmal",
  //   imageUrl: "/images/excom/2025/dasun-sri-nethmal.jpg",
  //   title: "Creative Content Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Yasiru Dharmathilaka",
  //   imageUrl: "/images/excom/2025/yasiru-dharmathilaka.jpg",
  //   title: "Development Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Sasindu Nilupul",
  //   imageUrl: "/images/excom/2025/sasindu-nilupul.jpg",
  //   title: "Research Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Anuja Rathnayaka",
  //   imageUrl: "/images/excom/2025/anuja-rathnayaka.jpg",
  //   title: "Creative Content Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Tharindu Thilakshana De Zoysa",
  //   imageUrl: "/images/excom/2025/tharindu-thilakshana-de-zoysa.jpg",
  //   title: "Creative Content Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Manuja Demin",
  //   imageUrl: "/images/excom/2025/manuja-demin.jpg",
  //   title: "Creative Content Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Ometh Abeyrathne",
  //   imageUrl: "/images/excom/2025/ometh-abeyrathne.jpg",
  //   title: "Development Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Navindu Disanayaka",
  //   imageUrl: "/images/excom/2025/navindu-disanayaka.jpg",
  //   title: "Development Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Nipun Avishka",
  //   imageUrl: "/images/excom/2025/nipun-avishka.jpg",
  //   title: "Development Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Navodhya Senali",
  //   imageUrl: "/images/excom/2025/navodhya-senali.jpg",
  //   title: "Research Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Malki Munasinghe",
  //   imageUrl: "/images/excom/2025/malki-munasinghe.jpg",
  //   title: "Research Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Sineth Hasintha",
  //   imageUrl: "/images/excom/2025/sineth-hasintha.jpg",
  //   title: "Research Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Lakindu Cabral",
  //   imageUrl: "/images/excom/2025/lakindu-cabral.jpg",
  //   title: "Research Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Udara Rathnapala",
  //   imageUrl: "/images/excom/2025/udara-rathnapala.jpg",
  //   title: "Research Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Nadeesha Thathsarani",
  //   imageUrl: "/images/excom/2025/nadeesha-thathsarani.jpg",
  //   title: "Research Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2025,
  //   name: "Prabani Vinodya",
  //   imageUrl: "/images/excom/2025/prabani-vinodya.jpg",
  //   title: "Research Committee Members",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Chathuranga Senarathne",
  //   imageUrl: "/images/excom/2024/chathuranga-senarathne.jpg",
  //   title: "Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Abhishek Rathnayaka",
  //   imageUrl: "/images/excom/2024/abhishek-rathnayaka.jpg",
  //   title: "Vice Chair-FOC",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Dewmi Hathurusingha",
  //   imageUrl: "/images/excom/2024/dewmi-hathurusingha.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Hansika Keeragala",
  //   imageUrl: "/images/excom/2024/hansika-keeragala.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Dhanuka Wickramage",
  //   imageUrl: "/images/excom/2024/dhanuka-wickramage.jpg",
  //   title: "Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Geeth Induwara",
  //   imageUrl: "/images/excom/2024/geeth-induwara.jpg",
  //   title: "Assistant Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Ishan Dulanjana",
  //   imageUrl: "/images/excom/2024/ishan-dulanjana.jpg",
  //   title: "Web Master",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Limasha Sathsara",
  //   imageUrl: "/images/excom/2024/limasha-sathsara.jpg",
  //   title: "Designer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Malinda Kawshalya",
  //   imageUrl: "/images/excom/2024/malinda-kawshalya.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Tharindu Dhanushka",
  //   imageUrl: "/images/excom/2024/tharindu-dhanushka.jpg",
  //   title: "Media Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Ishara Dias",
  //   imageUrl: "/images/excom/2024/ishara-dias.jpg",
  //   title: "Volunteer Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "sb",
  // },
  // {
  //   year: 2024,
  //   name: "Dewmi Hathurusingha",
  //   imageUrl: "/images/excom/2024/dewmi-hathurusingha.jpg",
  //   title: "Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Pasandi Samarasinghe",
  //   imageUrl: "/images/excom/2024/pasandi-samarasinghe.jpg",
  //   title: "Vice Chair - FOC",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Sewmini Lenora",
  //   imageUrl: "/images/excom/2024/sewmini-lenora.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Jasmi Pavithra",
  //   imageUrl: "/images/excom/2024/jasmi-pavithra.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Dasunika Yapabandara",
  //   imageUrl: "/images/excom/2024/dasunika-yapabandara.jpg",
  //   title: "Assistant Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Thathsarani Dhalanjala",
  //   imageUrl: "/images/excom/2024/thathsarani-dhalanjala.jpg",
  //   title: "Designer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Ayodya Weerabahu",
  //   imageUrl: "/images/excom/2024/ayodya-weerabahu.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Hiruni Athukorala",
  //   imageUrl: "/images/excom/2024/hiruni-athukorala.jpg",
  //   title: "Publicity Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "wie",
  // },
  // {
  //   year: 2024,
  //   name: "Abhishek Rathnayaka",
  //   imageUrl: "/images/excom/2024/abhishek-rathnayaka.jpg",
  //   title: "Chairperson",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Jayasanka Ariyarathna",
  //   imageUrl: "/images/excom/2024/jayasanka-ariyarathna.jpg",
  //   title: "Vice Chair-FOC",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Pasandi Samarasinghe",
  //   imageUrl: "/images/excom/2024/pasandi-samarasinghe.jpg",
  //   title: "Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Malinda Kawshalya",
  //   imageUrl: "/images/excom/2024/malinda-kawshalya.jpg",
  //   title: "Assistant Treasurer",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Githmi Senani",
  //   imageUrl: "/images/excom/2024/githmi-senani.jpg",
  //   title: "Assistant Secretary",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Kavishka Sasindu",
  //   imageUrl: "/images/excom/2024/kavishka-sasindu.jpg",
  //   title: "Event Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Geeth Induwara",
  //   imageUrl: "/images/excom/2024/geeth-induwara.jpg",
  //   title: "Industry Coordinator",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Ishara Bhagya",
  //   imageUrl: "/images/excom/2024/ishara-bhagya.jpg",
  //   title: "Creative Content Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Akshitha Sriyanjith",
  //   imageUrl: "/images/excom/2024/akshitha-sriyanjith.jpg",
  //   title: "Development Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Bakthi Gamage",
  //   imageUrl: "/images/excom/2024/bakthi-gamage.jpg",
  //   title: "Research Committee Lead",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Pramith Charuka",
  //   imageUrl: "/images/excom/2024/pramith-charuka.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Sithum Sankajith",
  //   imageUrl: "/images/excom/2024/sithum-sankajith.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Sasindu Nilupul",
  //   imageUrl: "/images/excom/2024/sasindu-nilupul.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Lahiru Nimesh Ediriweera",
  //   imageUrl: "/images/excom/2024/lahiru-nimesh-ediriweera.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Dulmin shanika wickramage",
  //   imageUrl: "/images/excom/2024/dulmin-shanika-wickramage.jpg",
  //   title: "Research Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Ranudi Kariyapperuma",
  //   imageUrl: "/images/excom/2024/ranudi-kariyapperuma.jpg",
  //   title: "Development Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Gayantha Nadeemal",
  //   imageUrl: "/images/excom/2024/gayantha-nadeemal.jpg",
  //   title: "Development Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
  // {
  //   year: 2024,
  //   name: "Ayodya Weerabahu",
  //   imageUrl: "/images/excom/2024/ayodya-weerabahu.jpg",
  //   title: "Creative Content Committee Member",
  //   linkdInURL: "",
  //   facebookURL: "",
  //   category: "cs",
  // },
];
